-- ====================================================================
-- SUPABASE POSTGRESQL SCHEMA FOR VOYAGER TRAVEL MANAGEMENT SYSTEM
-- ====================================================================

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. VOYAGE TABLE (PRIMARY TRAVEL & TRIP STORAGE)
-- Ensures the 'voyage' table exists and adds all required trip, itinerary,
-- budgeting, and booking fields:
CREATE TABLE IF NOT EXISTS public.voyage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.voyage
  ADD COLUMN IF NOT EXISTS trip_id TEXT,
  ADD COLUMN IF NOT EXISTS title TEXT,
  ADD COLUMN IF NOT EXISTS destination TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS country TEXT,
  ADD COLUMN IF NOT EXISTS additional_cities TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS start_date TEXT,
  ADD COLUMN IF NOT EXISTS end_date TEXT,
  ADD COLUMN IF NOT EXISTS is_flexible_dates BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS duration_days INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS travelers JSONB DEFAULT '{"adults": 1, "children": 0, "type": "Solo"}'::jsonb,
  ADD COLUMN IF NOT EXISTS budget_tier TEXT DEFAULT 'moderate',
  ADD COLUMN IF NOT EXISTS custom_budget_total NUMERIC(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS estimated_total_cost NUMERIC(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS travel_style TEXT DEFAULT 'balanced',
  ADD COLUMN IF NOT EXISTS pace TEXT DEFAULT 'balanced',
  ADD COLUMN IF NOT EXISTS cover_image TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'planning',
  ADD COLUMN IF NOT EXISTS days JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS accommodations JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS restaurants JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS budget_items JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS packing_items JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS travel_documents JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS destination_guide JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS raw_data JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS idx_voyage_trip_id ON public.voyage (trip_id);

ALTER TABLE public.voyage ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public access to voyage" ON public.voyage;
CREATE POLICY "Allow public access to voyage" ON public.voyage
  FOR ALL TO anon, authenticated
  USING (true)
  WITH CHECK (true);

-- 2. USER PROFILES TABLE
CREATE TABLE IF NOT EXISTS user_profiles (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  avatar TEXT,
  home_city TEXT,
  preferred_currency TEXT DEFAULT 'USD',
  passport_expiry TEXT,
  emergency_contact TEXT,
  saved_destinations TEXT[] DEFAULT '{}',
  preferences JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. DESTINATIONS CATALOG TABLE
CREATE TABLE IF NOT EXISTS destinations (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  country TEXT NOT NULL,
  tagline TEXT,
  category TEXT,
  image_url TEXT,
  rating NUMERIC(3, 2) DEFAULT 4.8,
  reviews_count INTEGER DEFAULT 0,
  best_time_to_visit TEXT,
  avg_daily_budget NUMERIC(10, 2) DEFAULT 150,
  currency TEXT DEFAULT 'USD',
  popular_activities TEXT[] DEFAULT '{}',
  trending BOOLEAN DEFAULT FALSE,
  featured BOOLEAN DEFAULT FALSE,
  hidden_gem BOOLEAN DEFAULT FALSE,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TRIPS TABLE
CREATE TABLE IF NOT EXISTS trips (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES user_profiles(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  destination TEXT NOT NULL,
  city TEXT NOT NULL,
  country TEXT NOT NULL,
  additional_cities TEXT[] DEFAULT '{}',
  cover_image TEXT,
  start_date TEXT,
  end_date TEXT,
  is_flexible_dates BOOLEAN DEFAULT FALSE,
  duration_days INTEGER DEFAULT 1,
  travelers JSONB DEFAULT '{"adults": 1, "children": 0, "infants": 0}'::jsonb,
  budget_tier TEXT DEFAULT 'Moderate',
  custom_budget_total NUMERIC(12, 2),
  estimated_total_cost NUMERIC(12, 2),
  travel_style TEXT DEFAULT 'Balanced',
  interests TEXT[] DEFAULT '{}',
  preferences JSONB DEFAULT '{}'::jsonb,
  overview JSONB DEFAULT '{}'::jsonb,
  status TEXT DEFAULT 'Draft' CHECK (status IN ('Draft', 'Upcoming', 'Active', 'Completed')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TRIP DAYS TABLE
CREATE TABLE IF NOT EXISTS trip_days (
  id TEXT PRIMARY KEY,
  trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  day_number INTEGER NOT NULL,
  date TEXT,
  title TEXT NOT NULL,
  theme TEXT,
  highlights TEXT[] DEFAULT '{}',
  summary TEXT,
  estimated_daily_cost NUMERIC(10, 2) DEFAULT 0,
  weather_forecast JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ACTIVITIES TABLE
CREATE TABLE IF NOT EXISTS activities (
  id TEXT PRIMARY KEY,
  trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  day_id TEXT REFERENCES trip_days(id) ON DELETE CASCADE,
  day_number INTEGER NOT NULL,
  sort_order INTEGER DEFAULT 0,
  time TEXT,
  title TEXT NOT NULL,
  location TEXT,
  duration TEXT,
  estimated_cost NUMERIC(10, 2) DEFAULT 0,
  cost_currency TEXT DEFAULT 'USD',
  distance_from_previous TEXT,
  transport_method TEXT,
  short_description TEXT,
  category TEXT DEFAULT 'sightseeing',
  coordinates JSONB,
  rating NUMERIC(3, 2),
  booking_recommended BOOLEAN DEFAULT FALSE,
  indoor_outdoor TEXT DEFAULT 'mixed',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. ACCOMMODATIONS TABLE
CREATE TABLE IF NOT EXISTS accommodations (
  id TEXT PRIMARY KEY,
  trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT,
  location TEXT,
  neighborhood TEXT,
  price_per_night NUMERIC(10, 2) DEFAULT 0,
  currency TEXT DEFAULT 'USD',
  rating NUMERIC(3, 2) DEFAULT 4.5,
  reviews_count INTEGER DEFAULT 0,
  image_url TEXT,
  amenities TEXT[] DEFAULT '{}',
  distance_to_center TEXT,
  distance_from_center TEXT,
  description TEXT,
  coordinates JSONB,
  badge TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. RESTAURANTS TABLE
CREATE TABLE IF NOT EXISTS restaurants (
  id TEXT PRIMARY KEY,
  trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  cuisine TEXT,
  price_range TEXT DEFAULT '$$',
  price_level TEXT,
  rating NUMERIC(3, 2) DEFAULT 4.5,
  location TEXT,
  description TEXT,
  specialty_dishes TEXT[] DEFAULT '{}',
  must_try_dishes TEXT[] DEFAULT '{}',
  dietary_tags TEXT[] DEFAULT '{}',
  is_vegetarian_friendly BOOLEAN DEFAULT FALSE,
  image_url TEXT,
  vibe TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. BUDGET ITEMS TABLE
CREATE TABLE IF NOT EXISTS budget_items (
  id TEXT PRIMARY KEY,
  trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  planned_amount NUMERIC(10, 2) DEFAULT 0,
  actual_amount NUMERIC(10, 2) DEFAULT 0,
  estimated_cost NUMERIC(10, 2) DEFAULT 0,
  actual_cost NUMERIC(10, 2) DEFAULT 0,
  is_paid BOOLEAN DEFAULT FALSE,
  notes TEXT,
  date TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. PACKING ITEMS TABLE
CREATE TABLE IF NOT EXISTS packing_items (
  id TEXT PRIMARY KEY,
  trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  is_packed BOOLEAN DEFAULT FALSE,
  is_custom BOOLEAN DEFAULT FALSE,
  quantity INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. TRAVEL DOCUMENTS TABLE
CREATE TABLE IF NOT EXISTS travel_documents (
  id TEXT PRIMARY KEY,
  trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  category TEXT,
  is_completed BOOLEAN DEFAULT FALSE,
  notes TEXT,
  expiry_date TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ====================================================================
-- PERFORMANCE INDEXES
-- ====================================================================
CREATE INDEX IF NOT EXISTS idx_trips_user_id ON trips(user_id);
CREATE INDEX IF NOT EXISTS idx_trips_status ON trips(status);
CREATE INDEX IF NOT EXISTS idx_trip_days_trip_id ON trip_days(trip_id);
CREATE INDEX IF NOT EXISTS idx_activities_trip_id ON activities(trip_id);
CREATE INDEX IF NOT EXISTS idx_activities_day_number ON activities(day_number);
CREATE INDEX IF NOT EXISTS idx_accommodations_trip_id ON accommodations(trip_id);
CREATE INDEX IF NOT EXISTS idx_restaurants_trip_id ON restaurants(trip_id);
CREATE INDEX IF NOT EXISTS idx_budget_items_trip_id ON budget_items(trip_id);
CREATE INDEX IF NOT EXISTS idx_packing_items_trip_id ON packing_items(trip_id);
CREATE INDEX IF NOT EXISTS idx_travel_documents_trip_id ON travel_documents(trip_id);

-- ====================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Permissive policies allowing client/server access with Supabase anon key
-- ====================================================================
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE destinations ENABLE ROW LEVEL SECURITY;
ALTER TABLE trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE accommodations ENABLE ROW LEVEL SECURITY;
ALTER TABLE restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE budget_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE packing_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE travel_documents ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  -- user_profiles
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_profiles' AND policyname = 'Public user_profiles access') THEN
    CREATE POLICY "Public user_profiles access" ON user_profiles FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- destinations
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'destinations' AND policyname = 'Public destinations access') THEN
    CREATE POLICY "Public destinations access" ON destinations FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- trips
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'trips' AND policyname = 'Public trips access') THEN
    CREATE POLICY "Public trips access" ON trips FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- trip_days
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'trip_days' AND policyname = 'Public trip_days access') THEN
    CREATE POLICY "Public trip_days access" ON trip_days FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- activities
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'activities' AND policyname = 'Public activities access') THEN
    CREATE POLICY "Public activities access" ON activities FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- accommodations
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'accommodations' AND policyname = 'Public accommodations access') THEN
    CREATE POLICY "Public accommodations access" ON accommodations FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- restaurants
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'restaurants' AND policyname = 'Public restaurants access') THEN
    CREATE POLICY "Public restaurants access" ON restaurants FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- budget_items
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'budget_items' AND policyname = 'Public budget_items access') THEN
    CREATE POLICY "Public budget_items access" ON budget_items FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- packing_items
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'packing_items' AND policyname = 'Public packing_items access') THEN
    CREATE POLICY "Public packing_items access" ON packing_items FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- travel_documents
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'travel_documents' AND policyname = 'Public travel_documents access') THEN
    CREATE POLICY "Public travel_documents access" ON travel_documents FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;
